version: "3.9"
services:
  bastion:
    image: "ghcr.io/dawnbrandbots/bastion-for-reddit:${DOCKER_TAG:-latest}"
    environment:
      REDDIT_CLIENT_ID:
      REDDIT_CLIENT_SECRET:
      REDDIT_USERNAME: BastionBotYuGiOh
      REDDIT_PASSWORD:
      SUBREDDITS: yugioh+YuGiOhMemes+Yugioh101+bastionbot+YuGiOhMasterDuel
      API_URL:
    logging:
      driver: "${DOCKER_LOG_DRIVER:-journald}"
    build: .
    restart: unless-stopped
